name: studypals
description: A comprehensive study companion app with flashcards, task management, and virtual pets.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^1.0.1+1
  path: ^1.8.3
  flutter_markdown: ^0.7.7+1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  intl: ^0.20.2
  fl_chart: ^1.1.0
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/FirstStudyPal.png
    - assets/dashboard_background.png