// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMGBRttLlv1E3kwXZNNZRgYfu-9wEKug',
    appId: '1:251508884392:web:7a842b1e9867506d09539d',
    messagingSenderId: '251508884392',
    projectId: 'studypals-9f7e1',
    authDomain: 'studypals-9f7e1.firebaseapp.com',
    storageBucket: 'studypals-9f7e1.appspot.com',
    measurementId: 'G-1J3NYP637K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMGBRttLlv1E3kwXZNNZRgYfu-9wEKug',
    appId: '1:251508884392:android:4d55ab8b067df67809539d',
    messagingSenderId: '251508884392',
    projectId: 'studypals-9f7e1',
    storageBucket: 'studypals-9f7e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALMGBRttLlv1E3kwXZNNZRgYfu-9wEKug',
    appId: '1:251508884392:ios:someappid09539d',
    messagingSenderId: '251508884392',
    projectId: 'studypals-9f7e1',
    storageBucket: 'studypals-9f7e1.firebasestorage.app',
    iosBundleId: 'com.example.studypals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALMGBRttLlv1E3kwXZNNZRgYfu-9wEKug',
    appId: '1:251508884392:ios:someappid09539d',
    messagingSenderId: '251508884392',
    projectId: 'studypals-9f7e1',
    storageBucket: 'studypals-9f7e1.firebasestorage.app',
    iosBundleId: 'com.example.studypals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALMGBRttLlv1E3kwXZNNZRgYfu-9wEKug',
    appId: '1:251508884392:web:7a842b1e9867506d09539d',
    messagingSenderId: '251508884392',
    projectId: 'studypals-9f7e1',
    authDomain: 'studypals-9f7e1.firebaseapp.com',
    storageBucket: 'studypals-9f7e1.appspot.com',
    measurementId: 'G-1J3NYP637K',
  );
}