// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMtyyIza1Ic42BHBs6eCYJi4u0GyeHXTs',
    appId: '1:832899771415:web:920bc56483b1fd452e4052',
    messagingSenderId: '832899771415',
    projectId: 'studypals-c4f44',
    authDomain: 'studypals-c4f44.firebaseapp.com',
    storageBucket: 'studypals-c4f44.firebasestorage.app',
    measurementId: 'G-VTY0KVSEBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3DtGyFslzAIMycwyGPbB0BIhc9Tm_AY8',
    appId: '1:832899771415:android:3d28f38b8f240ba02e4052',
    messagingSenderId: '832899771415',
    projectId: 'studypals-c4f44',
    storageBucket: 'studypals-c4f44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3DtGyFslzAIMycwyGPbB0BIhc9Tm_AY8',
    appId: '1:832899771415:ios:3d28f38b8f240ba02e4052',
    messagingSenderId: '832899771415',
    projectId: 'studypals-c4f44',
    storageBucket: 'studypals-c4f44.firebasestorage.app',
    iosBundleId: 'com.example.studypals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3DtGyFslzAIMycwyGPbB0BIhc9Tm_AY8',
    appId: '1:832899771415:ios:3d28f38b8f240ba02e4052',
    messagingSenderId: '832899771415',
    projectId: 'studypals-c4f44',
    storageBucket: 'studypals-c4f44.firebasestorage.app',
    iosBundleId: 'com.example.studypals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMtyyIza1Ic42BHBs6eCYJi4u0GyeHXTs',
    appId: '1:832899771415:web:d972b69e5f9308ab2e4052',
    messagingSenderId: '832899771415',
    projectId: 'studypals-c4f44',
    authDomain: 'studypals-c4f44.firebaseapp.com',
    storageBucket: 'studypals-c4f44.firebasestorage.app',
    measurementId: 'G-LJHQSFXGB0',
  );

}